# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

stage:
  -build

format-check:
  stage: build
  script:
    - MERGE_REQUEST_BASE=$(git merge-base origin/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME})
    - git clang-format $MERGE_REQUEST_BASE
    - git diff --exit-code
  only:
    changes:
      - "**/*.{cpp,c,cc,h,hh,hpp,tpp,ino}"
    refs:
        - merge_requests
        
.files-triggering-build:
  only:
    changes:
      - "**/*.{cpp,c,cc,fbs,h,hh,hpp,tpp,ino}"

build:
  extends: .files-triggering-build
  stage: build
  artifacts:
    expire_in: 2 days

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
